package hj.nerp.dao.vo;

// Generated Aug 18, 2014 3:49:55 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ctlm1342 generated by hbm2java
 */
public class Ctlm1342 implements java.io.Serializable {

	private String idSms;
	private String idCom;
	private String idSend;
	private String varMobile;
	private String varContent;
	private char flagSend;
	private Date dateSend;
	private Date dateOpr;
	private String idRecorder;
	private String varMobilename;
	private Date datePlansend;
	private Date dateLastsend;
	private String varErrmsg;

	public Ctlm1342() {
	}

	public Ctlm1342(String idSms, String idCom, String idSend,
			String varMobile, String varContent, char flagSend, Date dateSend,
			Date dateOpr, String idRecorder, String varMobilename,
			Date datePlansend, Date dateLastsend, String varErrmsg) {
		this.idSms = idSms;
		this.idCom = idCom;
		this.idSend = idSend;
		this.varMobile = varMobile;
		this.varContent = varContent;
		this.flagSend = flagSend;
		this.dateSend = dateSend;
		this.dateOpr = dateOpr;
		this.idRecorder = idRecorder;
		this.varMobilename = varMobilename;
		this.datePlansend = datePlansend;
		this.dateLastsend = dateLastsend;
		this.varErrmsg = varErrmsg;
	}

	public String getIdSms() {
		return this.idSms;
	}

	public void setIdSms(String idSms) {
		this.idSms = idSms;
	}

	public String getIdCom() {
		return this.idCom;
	}

	public void setIdCom(String idCom) {
		this.idCom = idCom;
	}

	public String getIdSend() {
		return this.idSend;
	}

	public void setIdSend(String idSend) {
		this.idSend = idSend;
	}

	public String getVarMobile() {
		return this.varMobile;
	}

	public void setVarMobile(String varMobile) {
		this.varMobile = varMobile;
	}

	public String getVarContent() {
		return this.varContent;
	}

	public void setVarContent(String varContent) {
		this.varContent = varContent;
	}

	public char getFlagSend() {
		return this.flagSend;
	}

	public void setFlagSend(char flagSend) {
		this.flagSend = flagSend;
	}

	public Date getDateSend() {
		return this.dateSend;
	}

	public void setDateSend(Date dateSend) {
		this.dateSend = dateSend;
	}

	public Date getDateOpr() {
		return this.dateOpr;
	}

	public void setDateOpr(Date dateOpr) {
		this.dateOpr = dateOpr;
	}

	public String getIdRecorder() {
		return this.idRecorder;
	}

	public void setIdRecorder(String idRecorder) {
		this.idRecorder = idRecorder;
	}

	public String getVarMobilename() {
		return this.varMobilename;
	}

	public void setVarMobilename(String varMobilename) {
		this.varMobilename = varMobilename;
	}

	public Date getDatePlansend() {
		return this.datePlansend;
	}

	public void setDatePlansend(Date datePlansend) {
		this.datePlansend = datePlansend;
	}

	public Date getDateLastsend() {
		return this.dateLastsend;
	}

	public void setDateLastsend(Date dateLastsend) {
		this.dateLastsend = dateLastsend;
	}

	public String getVarErrmsg() {
		return this.varErrmsg;
	}

	public void setVarErrmsg(String varErrmsg) {
		this.varErrmsg = varErrmsg;
	}

	@Override
	public String toString() {
		return "idSms:" + idSms + "varMobile:" + varMobile + "varContent:"
				+ varContent;
	}
}
